server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat

  # This will allow the browser to handle more parallel connections
  http2:
    enabled: true
